### ISSUE TITLE
Packages Needing Update

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#766]
These packages need updates:
- [x] blueimp-canvas-to-blob#2.1.1 (latest is 3.3.0)
- [ ] blueimp-file-upload#9.3.0 (latest is 9.12.1)
- [x] blueimp-load-image#1.13.0 (2.6.1 available)
- [ ] blueimp-tmpl#2.5.3 (3.3.0 available)
- [x] bootstrap-switch#1.8.0 (latest is 3.3.2)
- [x] jquery-validation#1.12.0 (latest is 1.15.0)
- [ ] semantic-ui-dropdown#1.10.3 (latest is 2.1.7)
- [ ] semantic-ui-transition#1.10.4 (latest is 2.1.7)
- [x] twbs-pagination#1.1.2 (latest is 1.3.1)
